import type { Metadata } from "next";
import "@radix-ui/themes/styles.css";
import "@/styles/theme.css";
import "./globals.css";
import { Theme } from "@radix-ui/themes";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import { Manrope, Plus_Jakarta_Sans } from "next/font/google";

const display = Plus_Jakarta_Sans({
  subsets: ["latin"],
  variable: "--font-display",
  weight: ["700", "800"],
});

const body = Manrope({
  subsets: ["latin"],
  variable: "--font-body",
  display: "swap",
  weight: ["400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className={`${body.variable} ${display.variable}`}>
      <body className="min-h-full flex flex-col">
        <Theme
          appearance="inherit"
          accentColor="iris"
          grayColor="mauve"
          radius="large"
          scaling="100%"
        >
          <SidebarProvider>
            <AppSidebar />
            <main className="bg-(--accent-3) w-full">
              <SidebarTrigger />
              {children}
            </main>
          </SidebarProvider>
        </Theme>
      </body>
    </html>
  );
}
